import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Bible App by Jason</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <p>The</p>
      <h1 className={styles.p}>Gospel of Mark</h1>
      <p className={styles.description}>
          
          <code className={styles.code}> Mark, the author of this gospel, probably was the first to write down the events of
          of Jesus life. It is believed that he is the same person who worked for many years as a missionary with Paul & Barnabas.</code>
          
        </p>
      <Image className={styles.christ1} src="/paul-writing-letters.jpeg" alt="title" width={1500} height={500}  />
        
       
        <p className={styles.description}>
          
          <code className={styles.code}> The book of Mark, which stresses facts & actions, rather than themes or topics, is the most exciting account of the life of Christ
                   among the Gospels. Although it is the shortest of the Gospels, it is often the most detailed. From the beginning, Mark tells the stories of Christs ministry, especially his miracles.
                   Mark shows Jesus as a man of action & authority. He spends one third of the book telling the events of Christs last week on earth, ending with the Saviors death & resurrection.
          </code>
          
        </p>
        <p className={styles.description}>
          
          <code className={styles.code}> Mark Chapter 1</code>
          
        </p>

        <div className={styles.grid}>
          <a href="javascript:void(0)" className={styles.card1}>
         
            <h1 className={styles.h1}>The Beginning of the Gospel &rarr;</h1>
            <p>The beginning of the good news about Jesus the Messiah, the Son of God, as it is written in Isaiah the prophet:</p>
            <Image className={styles.christ} src="/john_the_baptist2.jpeg" alt="title" width={200} height={200}  />
            <p>“I will send my messenger ahead of you,
    who will prepare your way” “a voice of one calling in the wilderness,
‘Prepare the way for the Lord,
    make straight paths for him.’”</p>
    
          </a>
        
          <a href="javascript:void(0)" className={styles.card1}>
            <h2 className={styles.h1} >John the Baptist Prepares the Way &rarr;</h2>

            <p>And so John the Baptist appeared in the wilderness, preaching a baptism of repentance for the forgiveness of sins. </p>
            <Image className={styles.christ} src="/john_the_baptist.jpeg" alt="title" width={200} height={200}  />
          <p>The whole Judean countryside and all the people of Jerusalem went out to him. Confessing their sins, they were baptized by him in the Jordan River.</p>
          <p>John wore clothing made of camel’s hair, with a leather belt around his waist, and he ate locusts and wild honey.</p>
          </a>

          <a
            href="javascript:void(0)"
            className={styles.card1}
          >
            <h2 className={styles.h1}> The Message &rarr;</h2>
            <p>And this was his message: “After me comes the one more powerful than I, the straps of whose sandals I am not worthy to stoop down and untie.</p>
            <p>I baptize you with water, but he will baptize you with the Holy Spirit.”</p>
            <p>
            <Image className={styles.christ} src="/jesus-baptism-main.jpeg" alt="title" width={200} height={200}  />
            At that time Jesus came from Nazareth in Galilee and was baptized by John in the Jordan.
            </p>
            <p>Just as Jesus was coming up out of the water, he saw heaven being torn open and the Spirit descending on him like a dove.</p>
          </a>

          <a
            href="javascript:void(0)"
            className={styles.card1}
          >
            <h1 className={styles.h1}>The Testing of Jesus &rarr;</h1>
            <Image className={styles.christ} src="/wilderness.jpeg" alt="Vercel Logo" width={300} height={300} />
          <p>At once the Spirit sent him out into the wilderness, and he was in the wilderness forty days, being tempted by Satan. He was with the wild animals, and angels attended him.</p>
         <p>After John was put in prison, Jesus went into Galilee, proclaiming the good news of God.</p>
         <p>“The time has come,” he said. “The kingdom of God has come near. Repent and believe the good news!”</p>
          </a>

          <a
            href="javascript:void(0)"
            className={styles.card1}
          >
            <h1 className={styles.h1}> Jesus Calls His First Disciples &rarr;</h1>
            <Image className={styles.christ} src="/disciples.jpeg" alt="Vercel Logo" width={300} height={300} />
           
<p>As Jesus walked beside the Sea of Galilee, he saw Simon and his brother Andrew casting a net into the lake, for they were fishermen. “Come, follow me,” Jesus said, “and I will send you out to fish for people.” At once they left their nets and followed him.</p>

 <p>When he had gone a little farther, he saw James son of Zebedee and his brother John in a boat, preparing their nets. Without delay he called them, and they left their father Zebedee in the boat with the hired men and followed him.</p>
          </a>
        </div>










        <div className={styles.grid}>
          <a href="javascript:void(0)" className={styles.card1}>
         
            <h1 className={styles.h1}>Jesus Drives Out an Impure Spirit
 &rarr;</h1>
            <p>They went to Capernaum, and when the Sabbath came, Jesus went into the synagogue and began to teach.</p>
           
            <p>The people were amazed at his teaching, because he taught them as one who had authority, not as the teachers of the law.</p>
    <p>Just then a man in their synagogue who was possessed by an impure spirit cried out, “What do you want with us, Jesus of Nazareth?</p>
    <Image className={styles.christ} src="/impure_spirit.jpeg" alt="title" width={200} height={200}  />
          <p>Have you come to destroy us? I know who you are—the Holy One of God!” “Be quiet!” said Jesus sternly. “Come out of him!” The impure spirit shook the man violently and came out of him with a shriek.</p>
          <p>The people were all so amazed that they asked each other, “What is this? A new teaching—and with authority! He even gives orders to impure spirits and they obey him.” News about him spread quickly over the whole region of Galilee.</p>
          </a>
        
          <a href="javascript:void(0)" className={styles.card1}>
            <h2 className={styles.h1} >Jesus Heals Many &rarr;</h2>

            <p>As soon as they left the synagogue, they went with James and John to the home of Simon and Andrew. </p>
            <Image className={styles.christ} src="/simon_mother_in_law.jpeg" alt="title" width={200} height={200}  />
          <p>Simon’s mother-in-law was in bed with a fever, and they immediately told Jesus about her.</p>
          <p>So he went to her, took her hand and helped her up. The fever left her and she began to wait on them.</p>
          <p>That evening after sunset the people brought to Jesus all the sick and demon-possessed. The whole town gathered at the door, and Jesus healed many who had various diseases. He also drove out many demons, but he would not let the demons speak because they knew who he was.

</p>
          </a>

          <a
            href="javascript:void(0)"
            className={styles.card1}
          >
            <h2 className={styles.h1}> Jesus Prays in a Solitary Place &rarr;</h2>
            <p>Very early in the morning, while it was still dark, Jesus got up, left the house and went off to a solitary place, where he prayed.</p>
            <p>Simon and his companions went to look for him, and when they found him, they exclaimed: “Everyone is looking for you!”</p>
            <p>
            <Image className={styles.christ} src="/solitary.jpeg" alt="title" width={200} height={200}  />
            Jesus replied, “Let us go somewhere else—to the nearby villages—so I can preach there also. That is why I have come.”
            </p>
            <p>So he traveled throughout Galilee, preaching in their synagogues and driving out demons.</p>
          </a>

          <a
            href="javascript:void(0)"
            className={styles.card1}
          >
            <h1 className={styles.h1}>Jesus Heals a Man With Leprosy &rarr;</h1>
           
          <p>A man with leprosy came to him and begged him on his knees, “If you are willing, you can make me clean.”</p>
         <p>Jesus was indignant. He reached out his hand and touched the man. “I am willing,” he said. “Be clean!”</p>
         <p>Immediately the leprosy left him and he was cleansed.</p>
         <Image className={styles.christ} src="/healing_a_leper.jpeg" alt="Vercel Logo" width={300} height={300} />
         <p>Jesus sent him away at once with a strong warning: “See that you don’t tell this to anyone. But go, show yourself to the priest and offer the sacrifices that Moses commanded for your cleansing, as a testimony to them.”</p>
         <p>Instead he went out and began to talk freely, spreading the news. As a result, Jesus could no longer enter a town openly but stayed outside in lonely places.</p> <p>Yet the people still came to him from everywhere.
         </p>
          
          </a>

     
        </div>
<p>The</p>
        <h1 className={styles.p}>Gospel of Mark </h1>
      <Image className={styles.christ1} src="/paul-writing-letters.jpeg" alt="title" width={1500} height={500}  />
        
      
        
        <p className={styles.description}>
          
          <code className={styles.code}> Mark Chapter 2</code>
          
        </p>







        <div className={styles.grid}>
          <a href="javascript:void(0)" className={styles.card1}>
         
            <h1 className={styles.h1}>
            Jesus Forgives a Paralyzed Man`s sins &rarr;</h1>
            <p>A few days later, when Jesus again entered Capernaum, the people heard that he had come home. </p>
    <p>They gathered in such large numbers that there was no room left, not even outside the door, and he preached the word to them. Some men came, bringing to him a paralyzed man, carried by four of them.</p>
    <Image className={styles.christ} src="/paralytic.jpeg" alt="title" width={200} height={200}  />
          <p>Since they could not get him to Jesus because of the crowd, they made an opening in the roof above Jesus by digging through it and then lowered the mat the man was lying on. When Jesus saw their faith, he said to the paralyzed man, “Son, your sins are forgiven.”</p>
        </a>
        
        <a href="javascript:void(0)" className={styles.card1}>
         
         <h1 className={styles.h1}>
         Jesus Heals a Paralyzed Man &rarr;</h1>
        <p>Now some teachers of the law were sitting there, thinking to themselves, “Why does this fellow talk like that? He’s blaspheming! Who can forgive sins but God alone?”</p>
        <Image className={styles.christ} src="/pharisees.jpeg" alt="title" width={200} height={200}  />
         <p>Immediately Jesus knew in his spirit that this was what they were thinking in their hearts, and he said to them, “Why are you thinking these things? Which is easier: to say to this paralyzed man, ‘Your sins are forgiven,’ or to say, ‘Get up, take your mat and walk’? </p>
         <p>But I want you to know that the Son of Man has authority on earth to forgive sins.” So he said to the man, “I tell you, get up, take your mat and go home.” He got up, took his mat and walked out in full view of them all. This amazed everyone and they praised God, saying, “We have never seen anything like this!”</p>
         </a>


          <a href="javascript:void(0)" className={styles.card1}>
            <h2 className={styles.h1} >Jesus Calls Levi and Eats With Sinners &rarr;</h2>

            <p>Once again Jesus went out beside the lake. A large crowd came to him, and he began to teach them. As he walked along, he saw Levi son of Alphaeus sitting at the tax collector’s booth. “Follow me,” Jesus told him, and Levi got up and followed him. </p>
            <Image className={styles.christ} src="/jesus_eats.jpeg" alt="title" width={200} height={200}  />
          <p>While Jesus was having dinner at Levi’s house, many tax collectors and sinners were eating with him and his disciples, for there were many who followed him. </p>
          <p>When the teachers of the law who were Pharisees saw him eating with the sinners and tax collectors, they asked his disciples: “Why does he eat with tax collectors and sinners?”</p>
          <p>On hearing this, Jesus said to them, “It is not the healthy who need a doctor, but the sick. I have not come to call the righteous, but sinners.”</p>
          </a>
          
          <a
            href="javascript:void(0)"
            className={styles.card1}
          >
            <h2 className={styles.h1}> Jesus Questioned About Fasting &rarr;</h2>
            <p>Now John’s disciples and the Pharisees were fasting. Some people came and asked Jesus, “How is it that John’s disciples and the disciples of the Pharisees are fasting, but yours are not?”</p>
            <p>Jesus answered, “How can the guests of the bridegroom fast while he is with them? They cannot, so long as they have him with them. But the time will come when the bridegroom will be taken from them, and on that day they will fast.</p>
            <p>
            <Image className={styles.christ} src="/new_wine.jpeg" alt="title" width={200} height={200}  />
            “No one sews a patch of unshrunk cloth on an old garment. Otherwise, the new piece will pull away from the old, making the tear worse.
            </p>
            <p>And no one pours new wine into old wineskins. Otherwise, the wine will burst the skins, and both the wine and the wineskins will be ruined. No, they pour new wine into new wineskins.”</p>
          </a>

          <a
            href="javascript:void(0)"
            className={styles.card1}
          >
            <h1 className={styles.h1}>Jesus Is Lord of the Sabbath &rarr;</h1>
           
          <p>One Sabbath Jesus was going through the grainfields, and as his disciples walked along, they began to pick some heads of grain. </p>
         <p>The Pharisees said to him, “Look, why are they doing what is unlawful on the Sabbath?”</p>
         <p>He answered, “Have you never read what David did when he and his companions were hungry and in need? </p>
         <Image className={styles.christ} src="/lord_of_sabbatth.jpeg" alt="Vercel Logo" width={300} height={300} />
         <p> In the days of Abiathar the high priest, he entered the house of God and ate the consecrated bread, which is lawful only for priests to eat. And he also gave some to his companions.”</p>
         <p>Then he said to them, “The Sabbath was made for man, not man for the Sabbath. So the Son of Man is Lord even of the Sabbath.”</p>
          
          </a>

     
        </div>





<p>The</p>
        <h1 className={styles.p}>Gospel of Mark </h1>
      <Image className={styles.christ1} src="/paul-writing-letters.jpeg" alt="title" width={1500} height={500}  />
        
      
        
        <p className={styles.description}>
          
          <code className={styles.code}> Mark Chapter 3</code>
          
        </p>







        <div className={styles.grid}>
          <a href="javascript:void(0)" className={styles.card1}>
         
            <h1 className={styles.h1}>
            Jesus Heals on the Sabbath &rarr;</h1>
            <Image className={styles.christ} src="/Man-with-withered-hand.jpeg" alt="jesus"  width={200} height={200}  />
            <p> Another time Jesus went into the synagogue, and a man with a shriveled hand was there. </p>
            <p>  Some of them were looking for a reason to accuse Jesus, so they watched him closely to see if he would heal him on the Sabbath.</p>
            <p> Jesus said to the man with the shriveled hand, “Stand up in front of everyone.”</p>
            <Image className={styles.christ} src="/shriveled_hand.jpeg" alt="title" width={200} height={200}  />
            <p>Then Jesus asked them, “Which is lawful on the Sabbath: to do good or to do evil, to save life or to kill?” But they remained silent.</p>
            <p>He looked around at them in anger and, deeply distressed at their stubborn hearts, said to the man, “Stretch out your hand.” He stretched it out, and his hand was completely restored. Then the Pharisees went out and began to plot with the Herodians how they might kill Jesus.</p>
        </a>
        
        <a href="javascript:void(0)" className={styles.card1}>
         
         <h1 className={styles.h1}>
         Crowds Follow Jesus &rarr;</h1>
        <p>Jesus withdrew with his disciples to the lake, and a large crowd from Galilee followed. </p>
        <Image className={styles.christ} src="/smallboat.jpeg" alt="title" width={200} height={200}  />
        <p>When they heard about all he was doing, many people came to him from Judea, Jerusalem, Idumea, and the regions across the Jordan and around Tyre and Sidon. </p>
        <p>Because of the crowd he told his disciples to have a small boat ready for him, to keep the people from crowding him.</p>
        <p>For he had healed many, so that those with diseases were pushing forward to touch him. </p>
        <Image className={styles.christ} src="/Monastic.png" alt="jesus"  width={200} height={200}  />
        <p>Whenever the impure spirits saw him, they fell down before him and cried out, “You are the Son of God.” But he gave them strict orders not to tell others about him.</p>
        </a>


          <a href="javascript:void(0)" className={styles.card1}>
            <h2 className={styles.h1} >Jesus Appoints the Twelve &rarr;</h2>
            <Image className={styles.christ} src="/twelve.jpeg" alt="jesus"  width={200} height={200}  />
            <p> Jesus went up on a mountainside and called to him those he wanted, and they came to him.</p>
            <Image className={styles.christ} src="/disciples2.jpeg" alt="title" width={200} height={200}  />
            <p>  He appointed twelve that they might be with him and that he might send them out to preach and to have authority to drive out demons.</p>
            <p> These are the twelve he appointed: Simon (to whom he gave the name Peter), James son of Zebedee and his brother John (to them he gave the name Boanerges, which means “sons of thunder”), Andrew, Philip, Bartholomew, Matthew, Thomas, James son of Alphaeus, Thaddaeus, Simon the Zealot and Judas Iscariot, who betrayed him.</p>
           
 </a>
          
          <a
            href="javascript:void(0)"
            className={styles.card1}
          >
            <h2 className={styles.h1}> Jesus Accused by His Family and by Teachers of the Law &rarr;</h2>
          <p>Then Jesus entered a house, and again a crowd gathered, so that he and his disciples were not even able to eat. When his family heard about this, they went to take charge of him, for they said, “He is out of his mind.”</p>
            <p>
            <Image className={styles.christ} src="/family.jpeg" alt="title" width={200} height={200}  />
            And the teachers of the law who came down from Jerusalem said, “He is possessed by Beelzebul! By the prince of demons he is driving out demons.”
            </p>
            <p> So Jesus called them over to him and began to speak to them in parables: “How can Satan drive out Satan? </p>
            <p> If a kingdom is divided against itself, that kingdom cannot stand. If a house is divided against itself, that house cannot stand. </p>
            <p> And if Satan opposes himself and is divided, he cannot stand; his end has come. In fact, no one can enter a strong man’s house without first tying him up. Then he can plunder the strong man’s house.</p>
            <p> Truly I tell you, people can be forgiven all their sins and every slander they utter, but whoever blasphemes against the Holy Spirit will never be forgiven; they are guilty of an eternal sin.”</p>
            <p> He said this because they were saying, “He has an impure spirit.”</p>
            <p> Then Jesus’ mother and brothers arrived. Standing outside, they sent someone in to call him. A crowd was sitting around him, and they told him, “Your mother and brothers are outside looking for you.”</p>
            <p> “Who are my mother and my brothers?” he asked. Then he looked at those seated in a circle around him and said, “Here are my mother and my brothers! Whoever does God’s will is my brother and sister and mother.”</p>
         
          </a>

         

     
        </div>






    <p>The</p>
        <h1 className={styles.p}>Gospel of Mark </h1>
      <Image className={styles.christ1} src="/6-sad-jesus-christ-cartoon-clipart.jpeg" alt="title" width={500} height={500}  />
        
      
        
        <p className={styles.description}>
          
          <code className={styles.code}> Mark Chapter 4</code>
          
        </p>







        <div className={styles.grid}>
          <a href="javascript:void(0)" className={styles.card1}>
         
            <h1 className={styles.h1}>
            Jesus  &rarr;</h1>
            <Image className={styles.christ} src="/thumbs_up.jpeg" alt="jesus"  width={200} height={200}  />
            <p>  </p>
            <p>  </p>
            <p> ”</p>
            <Image className={styles.christ} src="/2-jesus-christ-praying-on-his-knees-cartoon-clipart.jpeg" alt="title" width={200} height={200}  />
            <p> </p>
            <p> </p>
        </a>
        
        <a href="javascript:void(0)" className={styles.card1}>
         
         <h1 className={styles.h1}>
          Jesus &rarr;</h1>
        <p> </p>
        <Image className={styles.christ} src="/2-jesus-christ-praying-on-his-knees-cartoon-clipart.jpeg" alt="title" width={200} height={200}  />
        <p> </p>
        <p> </p>
        <p> </p>
        <Image className={styles.christ} src="/peace_jesus.jpeg" alt="jesus"  width={200} height={200}  />
        <p> </p>
        </a>


          <a href="javascript:void(0)" className={styles.card1}>
            <h2 className={styles.h1} >Jesus  &rarr;</h2>
            <Image className={styles.christ} src="/6-sad-jesus-christ-cartoon-clipart.jpeg" alt="jesus"  width={200} height={200}  />
            <p> </p>
            <Image className={styles.christ} src="/1-jesus-christ-with-arms-wide-open-cartoon-clipart.jpeg" alt="title" width={200} height={200}  />
            <p> </p>
            <p> </p>
           
 </a>
          
          <a
            href="javascript:void(0)"
            className={styles.card1}
          >
            <h2 className={styles.h1}> Jesus  &rarr;</h2>
          <p></p>
            <p>
            <Image className={styles.christ} src="/worship_jesus.jpeg" alt="title" width={200} height={200}  />
           Sentence goes here
            </p>
            <p>  </p>
            <p> </p>
            <p> </p>
            <p> </p>
            <p> </p>
            
          </a>

         

     
        </div>




        <p>The</p>
        <h1 className={styles.p}>Gospel of Mark </h1>
      <Image className={styles.christ1} src="/6-sad-jesus-christ-cartoon-clipart.jpeg" alt="title" width={500} height={500}  />
        
      
        
        <p className={styles.description}>
          
          <code className={styles.code}> Mark Chapter 5</code>
          
        </p>







        <div className={styles.grid}>
          <a href="javascript:void(0)" className={styles.card1}>
         
            <h1 className={styles.h1}>
            Jesus  &rarr;</h1>
            <Image className={styles.christ} src="/thumbs_up.jpeg" alt="jesus"  width={200} height={200}  />
            <p>  </p>
            <p>  </p>
            <p> ”</p>
            <Image className={styles.christ} src="/2-jesus-christ-praying-on-his-knees-cartoon-clipart.jpeg" alt="title" width={200} height={200}  />
            <p> </p>
            <p> </p>
        </a>
        
        <a href="javascript:void(0)" className={styles.card1}>
         
         <h1 className={styles.h1}>
          Jesus &rarr;</h1>
        <p> </p>
        <Image className={styles.christ} src="/2-jesus-christ-praying-on-his-knees-cartoon-clipart.jpeg" alt="title" width={200} height={200}  />
        <p> </p>
        <p> </p>
        <p> </p>
        <Image className={styles.christ} src="/peace_jesus.jpeg" alt="jesus"  width={200} height={200}  />
        <p> </p>
        </a>


          <a href="javascript:void(0)" className={styles.card1}>
            <h2 className={styles.h1} >Jesus  &rarr;</h2>
            <Image className={styles.christ} src="/6-sad-jesus-christ-cartoon-clipart.jpeg" alt="jesus"  width={200} height={200}  />
            <p> </p>
            <Image className={styles.christ} src="/1-jesus-christ-with-arms-wide-open-cartoon-clipart.jpeg" alt="title" width={200} height={200}  />
            <p> </p>
            <p> </p>
           
 </a>
          
          <a
            href="javascript:void(0)"
            className={styles.card1}
          >
            <h2 className={styles.h1}> Jesus  &rarr;</h2>
          <p></p>
            <p>
            <Image className={styles.christ} src="/worship_jesus.jpeg" alt="title" width={200} height={200}  />
           Sentence goes here
            </p>
            <p>  </p>
            <p> </p>
            <p> </p>
            <p> </p>
            <p> </p>
            
          </a>

         

     
        </div>



        <p>The</p>
        <h1 className={styles.p}>Gospel of Mark </h1>
      <Image className={styles.christ1} src="/6-sad-jesus-christ-cartoon-clipart.jpeg" alt="title" width={500} height={500}  />
        
      
        
        <p className={styles.description}>
          
          <code className={styles.code}> Mark Chapter 6</code>
          
        </p>







        <div className={styles.grid}>
          <a href="javascript:void(0)" className={styles.card1}>
         
            <h1 className={styles.h1}>
            Jesus  &rarr;</h1>
            <Image className={styles.christ} src="/thumbs_up.jpeg" alt="jesus"  width={200} height={200}  />
            <p>  </p>
            <p>  </p>
            <p> ”</p>
            <Image className={styles.christ} src="/2-jesus-christ-praying-on-his-knees-cartoon-clipart.jpeg" alt="title" width={200} height={200}  />
            <p> </p>
            <p> </p>
        </a>
        
        <a href="javascript:void(0)" className={styles.card1}>
         
         <h1 className={styles.h1}>
          Jesus &rarr;</h1>
        <p> </p>
        <Image className={styles.christ} src="/2-jesus-christ-praying-on-his-knees-cartoon-clipart.jpeg" alt="title" width={200} height={200}  />
        <p> </p>
        <p> </p>
        <p> </p>
        <Image className={styles.christ} src="/peace_jesus.jpeg" alt="jesus"  width={200} height={200}  />
        <p> </p>
        </a>


          <a href="javascript:void(0)" className={styles.card1}>
            <h2 className={styles.h1} >Jesus  &rarr;</h2>
            <Image className={styles.christ} src="/6-sad-jesus-christ-cartoon-clipart.jpeg" alt="jesus"  width={200} height={200}  />
            <p> </p>
            <Image className={styles.christ} src="/1-jesus-christ-with-arms-wide-open-cartoon-clipart.jpeg" alt="title" width={200} height={200}  />
            <p> </p>
            <p> </p>
           
 </a>
          
          <a
            href="javascript:void(0)"
            className={styles.card1}
          >
            <h2 className={styles.h1}> Jesus  &rarr;</h2>
          <p></p>
            <p>
            <Image className={styles.christ} src="/worship_jesus.jpeg" alt="title" width={200} height={200}  />
           Sentence goes here
            </p>
            <p>  </p>
            <p> </p>
            <p> </p>
            <p> </p>
            <p> </p>
            
          </a>

         

     
        </div>




        <p>The</p>
        <h1 className={styles.p}>Gospel of Mark </h1>
      <Image className={styles.christ1} src="/6-sad-jesus-christ-cartoon-clipart.jpeg" alt="title" width={500} height={500}  />
        
      
        
        <p className={styles.description}>
          
          <code className={styles.code}> Mark Chapter 7</code>
          
        </p>







        <div className={styles.grid}>
          <a href="javascript:void(0)" className={styles.card1}>
         
            <h1 className={styles.h1}>
            Jesus  &rarr;</h1>
            <Image className={styles.christ} src="/thumbs_up.jpeg" alt="jesus"  width={200} height={200}  />
            <p>  </p>
            <p>  </p>
            <p> ”</p>
            <Image className={styles.christ} src="/2-jesus-christ-praying-on-his-knees-cartoon-clipart.jpeg" alt="title" width={200} height={200}  />
            <p> </p>
            <p> </p>
        </a>
        
        <a href="javascript:void(0)" className={styles.card1}>
         
         <h1 className={styles.h1}>
          Jesus &rarr;</h1>
        <p> </p>
        <Image className={styles.christ} src="/2-jesus-christ-praying-on-his-knees-cartoon-clipart.jpeg" alt="title" width={200} height={200}  />
        <p> </p>
        <p> </p>
        <p> </p>
        <Image className={styles.christ} src="/peace_jesus.jpeg" alt="jesus"  width={200} height={200}  />
        <p> </p>
        </a>


          <a href="javascript:void(0)" className={styles.card1}>
            <h2 className={styles.h1} >Jesus  &rarr;</h2>
            <Image className={styles.christ} src="/6-sad-jesus-christ-cartoon-clipart.jpeg" alt="jesus"  width={200} height={200}  />
            <p> </p>
            <Image className={styles.christ} src="/1-jesus-christ-with-arms-wide-open-cartoon-clipart.jpeg" alt="title" width={200} height={200}  />
            <p> </p>
            <p> </p>
           
 </a>
          
          <a
            href="javascript:void(0)"
            className={styles.card1}
          >
            <h2 className={styles.h1}> Jesus  &rarr;</h2>
          <p></p>
            <p>
            <Image className={styles.christ} src="/worship_jesus.jpeg" alt="title" width={200} height={200}  />
           Sentence goes here
            </p>
            <p>  </p>
            <p> </p>
            <p> </p>
            <p> </p>
            <p> </p>
            
          </a>

         

     
        </div>




        <p>The</p>
        <h1 className={styles.p}>Gospel of Mark </h1>
      <Image className={styles.christ1} src="/6-sad-jesus-christ-cartoon-clipart.jpeg" alt="title" width={500} height={500}  />
        
      
        
        <p className={styles.description}>
          
          <code className={styles.code}> Mark Chapter 8</code>
          
        </p>







        <div className={styles.grid}>
          <a href="javascript:void(0)" className={styles.card1}>
         
            <h1 className={styles.h1}>
            Jesus  &rarr;</h1>
            <Image className={styles.christ} src="/thumbs_up.jpeg" alt="jesus"  width={200} height={200}  />
            <p>  </p>
            <p>  </p>
            <p> ”</p>
            <Image className={styles.christ} src="/2-jesus-christ-praying-on-his-knees-cartoon-clipart.jpeg" alt="title" width={200} height={200}  />
            <p> </p>
            <p> </p>
        </a>
        
        <a href="javascript:void(0)" className={styles.card1}>
         
         <h1 className={styles.h1}>
          Jesus &rarr;</h1>
        <p> </p>
        <Image className={styles.christ} src="/2-jesus-christ-praying-on-his-knees-cartoon-clipart.jpeg" alt="title" width={200} height={200}  />
        <p> </p>
        <p> </p>
        <p> </p>
        <Image className={styles.christ} src="/peace_jesus.jpeg" alt="jesus"  width={200} height={200}  />
        <p> </p>
        </a>


          <a href="javascript:void(0)" className={styles.card1}>
            <h2 className={styles.h1} >Jesus  &rarr;</h2>
            <Image className={styles.christ} src="/6-sad-jesus-christ-cartoon-clipart.jpeg" alt="jesus"  width={200} height={200}  />
            <p> </p>
            <Image className={styles.christ} src="/1-jesus-christ-with-arms-wide-open-cartoon-clipart.jpeg" alt="title" width={200} height={200}  />
            <p> </p>
            <p> </p>
           
 </a>
          
          <a
            href="javascript:void(0)"
            className={styles.card1}
          >
            <h2 className={styles.h1}> Jesus  &rarr;</h2>
          <p></p>
            <p>
            <Image className={styles.christ} src="/worship_jesus.jpeg" alt="title" width={200} height={200}  />
           Sentence goes here
            </p>
            <p>  </p>
            <p> </p>
            <p> </p>
            <p> </p>
            <p> </p>
            
          </a>

         

     
        </div>







        <p>The</p>
        <h1 className={styles.p}>Gospel of Mark </h1>
      <Image className={styles.christ1} src="/6-sad-jesus-christ-cartoon-clipart.jpeg" alt="title" width={500} height={500}  />
        
      
        
        <p className={styles.description}>
          
          <code className={styles.code}> Mark Chapter 9</code>
          
        </p>







        <div className={styles.grid}>
          <a href="javascript:void(0)" className={styles.card1}>
         
            <h1 className={styles.h1}>
            Jesus  &rarr;</h1>
            <Image className={styles.christ} src="/thumbs_up.jpeg" alt="jesus"  width={200} height={200}  />
            <p>  </p>
            <p>  </p>
            <p> ”</p>
            <Image className={styles.christ} src="/2-jesus-christ-praying-on-his-knees-cartoon-clipart.jpeg" alt="title" width={200} height={200}  />
            <p> </p>
            <p> </p>
        </a>
        
        <a href="javascript:void(0)" className={styles.card1}>
         
         <h1 className={styles.h1}>
          Jesus &rarr;</h1>
        <p> </p>
        <Image className={styles.christ} src="/2-jesus-christ-praying-on-his-knees-cartoon-clipart.jpeg" alt="title" width={200} height={200}  />
        <p> </p>
        <p> </p>
        <p> </p>
        <Image className={styles.christ} src="/peace_jesus.jpeg" alt="jesus"  width={200} height={200}  />
        <p> </p>
        </a>


          <a href="javascript:void(0)" className={styles.card1}>
            <h2 className={styles.h1} >Jesus  &rarr;</h2>
            <Image className={styles.christ} src="/6-sad-jesus-christ-cartoon-clipart.jpeg" alt="jesus"  width={200} height={200}  />
            <p> </p>
            <Image className={styles.christ} src="/1-jesus-christ-with-arms-wide-open-cartoon-clipart.jpeg" alt="title" width={200} height={200}  />
            <p> </p>
            <p> </p>
           
 </a>
          
          <a
            href="javascript:void(0)"
            className={styles.card1}
          >
            <h2 className={styles.h1}> Jesus  &rarr;</h2>
          <p></p>
            <p>
            <Image className={styles.christ} src="/worship_jesus.jpeg" alt="title" width={200} height={200}  />
           Sentence goes here
            </p>
            <p>  </p>
            <p> </p>
            <p> </p>
            <p> </p>
            <p> </p>
            
          </a>

         

     
        </div>





        <p>The</p>
        <h1 className={styles.p}>Gospel of Mark </h1>
      <Image className={styles.christ1} src="/6-sad-jesus-christ-cartoon-clipart.jpeg" alt="title" width={500} height={500}  />
        
      
        
        <p className={styles.description}>
          
          <code className={styles.code}> Mark Chapter 10</code>
          
        </p>







        <div className={styles.grid}>
          <a href="javascript:void(0)" className={styles.card1}>
         
            <h1 className={styles.h1}>
            Jesus  &rarr;</h1>
            <Image className={styles.christ} src="/thumbs_up.jpeg" alt="jesus"  width={200} height={200}  />
            <p>  </p>
            <p>  </p>
            <p> ”</p>
            <Image className={styles.christ} src="/2-jesus-christ-praying-on-his-knees-cartoon-clipart.jpeg" alt="title" width={200} height={200}  />
            <p> </p>
            <p> </p>
        </a>
        
        <a href="javascript:void(0)" className={styles.card1}>
         
         <h1 className={styles.h1}>
          Jesus &rarr;</h1>
        <p> </p>
        <Image className={styles.christ} src="/2-jesus-christ-praying-on-his-knees-cartoon-clipart.jpeg" alt="title" width={200} height={200}  />
        <p> </p>
        <p> </p>
        <p> </p>
        <Image className={styles.christ} src="/peace_jesus.jpeg" alt="jesus"  width={200} height={200}  />
        <p> </p>
        </a>


          <a href="javascript:void(0)" className={styles.card1}>
            <h2 className={styles.h1} >Jesus  &rarr;</h2>
            <Image className={styles.christ} src="/6-sad-jesus-christ-cartoon-clipart.jpeg" alt="jesus"  width={200} height={200}  />
            <p> </p>
            <Image className={styles.christ} src="/1-jesus-christ-with-arms-wide-open-cartoon-clipart.jpeg" alt="title" width={200} height={200}  />
            <p> </p>
            <p> </p>
           
 </a>
          
          <a
            href="javascript:void(0)"
            className={styles.card1}
          >
            <h2 className={styles.h1}> Jesus  &rarr;</h2>
          <p></p>
            <p>
            <Image className={styles.christ} src="/worship_jesus.jpeg" alt="title" width={200} height={200}  />
           Sentence goes here
            </p>
            <p>  </p>
            <p> </p>
            <p> </p>
            <p> </p>
            <p> </p>
            
          </a>

         

     
        </div>




        <p>The</p>
        <h1 className={styles.p}>Gospel of Mark </h1>
      <Image className={styles.christ1} src="/6-sad-jesus-christ-cartoon-clipart.jpeg" alt="title" width={500} height={500}  />
        
      
        
        <p className={styles.description}>
          
          <code className={styles.code}> Mark Chapter 11</code>
          
        </p>







        <div className={styles.grid}>
          <a href="javascript:void(0)" className={styles.card1}>
         
            <h1 className={styles.h1}>
            Jesus  &rarr;</h1>
            <Image className={styles.christ} src="/thumbs_up.jpeg" alt="jesus"  width={200} height={200}  />
            <p>  </p>
            <p>  </p>
            <p> ”</p>
            <Image className={styles.christ} src="/2-jesus-christ-praying-on-his-knees-cartoon-clipart.jpeg" alt="title" width={200} height={200}  />
            <p> </p>
            <p> </p>
        </a>
        
        <a href="javascript:void(0)" className={styles.card1}>
         
         <h1 className={styles.h1}>
          Jesus &rarr;</h1>
        <p> </p>
        <Image className={styles.christ} src="/2-jesus-christ-praying-on-his-knees-cartoon-clipart.jpeg" alt="title" width={200} height={200}  />
        <p> </p>
        <p> </p>
        <p> </p>
        <Image className={styles.christ} src="/peace_jesus.jpeg" alt="jesus"  width={200} height={200}  />
        <p> </p>
        </a>


          <a href="javascript:void(0)" className={styles.card1}>
            <h2 className={styles.h1} >Jesus  &rarr;</h2>
            <Image className={styles.christ} src="/6-sad-jesus-christ-cartoon-clipart.jpeg" alt="jesus"  width={200} height={200}  />
            <p> </p>
            <Image className={styles.christ} src="/1-jesus-christ-with-arms-wide-open-cartoon-clipart.jpeg" alt="title" width={200} height={200}  />
            <p> </p>
            <p> </p>
           
 </a>
          
          <a
            href="javascript:void(0)"
            className={styles.card1}
          >
            <h2 className={styles.h1}> Jesus  &rarr;</h2>
          <p></p>
            <p>
            <Image className={styles.christ} src="/worship_jesus.jpeg" alt="title" width={200} height={200}  />
           Sentence goes here
            </p>
            <p>  </p>
            <p> </p>
            <p> </p>
            <p> </p>
            <p> </p>
            
          </a>

         

     
        </div>



        <p>The</p>
        <h1 className={styles.p}>Gospel of Mark </h1>
      <Image className={styles.christ1} src="/6-sad-jesus-christ-cartoon-clipart.jpeg" alt="title" width={500} height={500}  />
        
      
        
        <p className={styles.description}>
          
          <code className={styles.code}> Mark Chapter 12</code>
          
        </p>







        <div className={styles.grid}>
          <a href="javascript:void(0)" className={styles.card1}>
         
            <h1 className={styles.h1}>
            Jesus  &rarr;</h1>
            <Image className={styles.christ} src="/thumbs_up.jpeg" alt="jesus"  width={200} height={200}  />
            <p>  </p>
            <p>  </p>
            <p> ”</p>
            <Image className={styles.christ} src="/2-jesus-christ-praying-on-his-knees-cartoon-clipart.jpeg" alt="title" width={200} height={200}  />
            <p> </p>
            <p> </p>
        </a>
        
        <a href="javascript:void(0)" className={styles.card1}>
         
         <h1 className={styles.h1}>
          Jesus &rarr;</h1>
        <p> </p>
        <Image className={styles.christ} src="/2-jesus-christ-praying-on-his-knees-cartoon-clipart.jpeg" alt="title" width={200} height={200}  />
        <p> </p>
        <p> </p>
        <p> </p>
        <Image className={styles.christ} src="/peace_jesus.jpeg" alt="jesus"  width={200} height={200}  />
        <p> </p>
        </a>


          <a href="javascript:void(0)" className={styles.card1}>
            <h2 className={styles.h1} >Jesus  &rarr;</h2>
            <Image className={styles.christ} src="/6-sad-jesus-christ-cartoon-clipart.jpeg" alt="jesus"  width={200} height={200}  />
            <p> </p>
            <Image className={styles.christ} src="/1-jesus-christ-with-arms-wide-open-cartoon-clipart.jpeg" alt="title" width={200} height={200}  />
            <p> </p>
            <p> </p>
           
 </a>
          
          <a
            href="javascript:void(0)"
            className={styles.card1}
          >
            <h2 className={styles.h1}> Jesus  &rarr;</h2>
          <p></p>
            <p>
            <Image className={styles.christ} src="/worship_jesus.jpeg" alt="title" width={200} height={200}  />
           Sentence goes here
            </p>
            <p>  </p>
            <p> </p>
            <p> </p>
            <p> </p>
            <p> </p>
            
          </a>

         

     
        </div>





        <p>The</p>
        <h1 className={styles.p}>Gospel of Mark </h1>
      <Image className={styles.christ1} src="/6-sad-jesus-christ-cartoon-clipart.jpeg" alt="title" width={500} height={500}  />
        
      
        
        <p className={styles.description}>
          
          <code className={styles.code}> Mark Chapter 13</code>
          
        </p>







        <div className={styles.grid}>
          <a href="javascript:void(0)" className={styles.card1}>
         
            <h1 className={styles.h1}>
            Jesus  &rarr;</h1>
            <Image className={styles.christ} src="/thumbs_up.jpeg" alt="jesus"  width={200} height={200}  />
            <p>  </p>
            <p>  </p>
            <p> ”</p>
            <Image className={styles.christ} src="/2-jesus-christ-praying-on-his-knees-cartoon-clipart.jpeg" alt="title" width={200} height={200}  />
            <p> </p>
            <p> </p>
        </a>
        
        <a href="javascript:void(0)" className={styles.card1}>
         
         <h1 className={styles.h1}>
          Jesus &rarr;</h1>
        <p> </p>
        <Image className={styles.christ} src="/2-jesus-christ-praying-on-his-knees-cartoon-clipart.jpeg" alt="title" width={200} height={200}  />
        <p> </p>
        <p> </p>
        <p> </p>
        <Image className={styles.christ} src="/peace_jesus.jpeg" alt="jesus"  width={200} height={200}  />
        <p> </p>
        </a>


          <a href="javascript:void(0)" className={styles.card1}>
            <h2 className={styles.h1} >Jesus  &rarr;</h2>
            <Image className={styles.christ} src="/6-sad-jesus-christ-cartoon-clipart.jpeg" alt="jesus"  width={200} height={200}  />
            <p> </p>
            <Image className={styles.christ} src="/1-jesus-christ-with-arms-wide-open-cartoon-clipart.jpeg" alt="title" width={200} height={200}  />
            <p> </p>
            <p> </p>
           
 </a>
          
          <a
            href="javascript:void(0)"
            className={styles.card1}
          >
            <h2 className={styles.h1}> Jesus  &rarr;</h2>
          <p></p>
            <p>
            <Image className={styles.christ} src="/worship_jesus.jpeg" alt="title" width={200} height={200}  />
           Sentence goes here
            </p>
            <p>  </p>
            <p> </p>
            <p> </p>
            <p> </p>
            <p> </p>
            
          </a>

         

     
        </div>





        <p>The</p>
        <h1 className={styles.p}>Gospel of Mark </h1>
      <Image className={styles.christ1} src="/6-sad-jesus-christ-cartoon-clipart.jpeg" alt="title" width={500} height={500}  />
        
      
        
        <p className={styles.description}>
          
          <code className={styles.code}> Mark Chapter 14</code>
          
        </p>







        <div className={styles.grid}>
          <a href="javascript:void(0)" className={styles.card1}>
         
            <h1 className={styles.h1}>
            Jesus  &rarr;</h1>
            <Image className={styles.christ} src="/thumbs_up.jpeg" alt="jesus"  width={200} height={200}  />
            <p>  </p>
            <p>  </p>
            <p> ”</p>
            <Image className={styles.christ} src="/2-jesus-christ-praying-on-his-knees-cartoon-clipart.jpeg" alt="title" width={200} height={200}  />
            <p> </p>
            <p> </p>
        </a>
        
        <a href="javascript:void(0)" className={styles.card1}>
         
         <h1 className={styles.h1}>
          Jesus &rarr;</h1>
        <p> </p>
        <Image className={styles.christ} src="/2-jesus-christ-praying-on-his-knees-cartoon-clipart.jpeg" alt="title" width={200} height={200}  />
        <p> </p>
        <p> </p>
        <p> </p>
        <Image className={styles.christ} src="/peace_jesus.jpeg" alt="jesus"  width={200} height={200}  />
        <p> </p>
        </a>


          <a href="javascript:void(0)" className={styles.card1}>
            <h2 className={styles.h1} >Jesus  &rarr;</h2>
            <Image className={styles.christ} src="/6-sad-jesus-christ-cartoon-clipart.jpeg" alt="jesus"  width={200} height={200}  />
            <p> </p>
            <Image className={styles.christ} src="/1-jesus-christ-with-arms-wide-open-cartoon-clipart.jpeg" alt="title" width={200} height={200}  />
            <p> </p>
            <p> </p>
           
 </a>
          
          <a
            href="javascript:void(0)"
            className={styles.card1}
          >
            <h2 className={styles.h1}> Jesus  &rarr;</h2>
          <p></p>
            <p>
            <Image className={styles.christ} src="/worship_jesus.jpeg" alt="title" width={200} height={200}  />
           Sentence goes here
            </p>
            <p>  </p>
            <p> </p>
            <p> </p>
            <p> </p>
            <p> </p>
            
          </a>

         

     
        </div>





        <p>The</p>
        <h1 className={styles.p}>Gospel of Mark </h1>
      <Image className={styles.christ1} src="/6-sad-jesus-christ-cartoon-clipart.jpeg" alt="title" width={500} height={500}  />
        
      
        
        <p className={styles.description}>
          
          <code className={styles.code}> Mark Chapter 15</code>
          
        </p>







        <div className={styles.grid}>
          <a href="javascript:void(0)" className={styles.card1}>
         
            <h1 className={styles.h1}>
            Jesus  &rarr;</h1>
            <Image className={styles.christ} src="/thumbs_up.jpeg" alt="jesus"  width={200} height={200}  />
            <p>  </p>
            <p>  </p>
            <p> ”</p>
            <Image className={styles.christ} src="/2-jesus-christ-praying-on-his-knees-cartoon-clipart.jpeg" alt="title" width={200} height={200}  />
            <p> </p>
            <p> </p>
        </a>
        
        <a href="javascript:void(0)" className={styles.card1}>
         
         <h1 className={styles.h1}>
          Jesus &rarr;</h1>
        <p> </p>
        <Image className={styles.christ} src="/2-jesus-christ-praying-on-his-knees-cartoon-clipart.jpeg" alt="title" width={200} height={200}  />
        <p> </p>
        <p> </p>
        <p> </p>
        <Image className={styles.christ} src="/peace_jesus.jpeg" alt="jesus"  width={200} height={200}  />
        <p> </p>
        </a>


          <a href="javascript:void(0)" className={styles.card1}>
            <h2 className={styles.h1} >Jesus  &rarr;</h2>
            <Image className={styles.christ} src="/6-sad-jesus-christ-cartoon-clipart.jpeg" alt="jesus"  width={200} height={200}  />
            <p> </p>
            <Image className={styles.christ} src="/1-jesus-christ-with-arms-wide-open-cartoon-clipart.jpeg" alt="title" width={200} height={200}  />
            <p> </p>
            <p> </p>
           
 </a>
          
          <a
            href="javascript:void(0)"
            className={styles.card1}
          >
            <h2 className={styles.h1}> Jesus  &rarr;</h2>
          <p></p>
            <p>
            <Image className={styles.christ} src="/worship_jesus.jpeg" alt="title" width={200} height={200}  />
           Sentence goes here
            </p>
            <p>  </p>
            <p> </p>
            <p> </p>
            <p> </p>
            <p> </p>
            
          </a>

         

     
        </div>



        <p>The</p>
        <h1 className={styles.p}>Gospel of Mark </h1>
      <Image className={styles.christ1} src="/6-sad-jesus-christ-cartoon-clipart.jpeg" alt="title" width={500} height={500}  />
        
      
        
        <p className={styles.description}>
          
          <code className={styles.code}> Mark Chapter 16</code>
          
        </p>







        <div className={styles.grid}>
          <a href="javascript:void(0)" className={styles.card1}>
         
            <h1 className={styles.h1}>
            Jesus  &rarr;</h1>
            <Image className={styles.christ} src="/thumbs_up.jpeg" alt="jesus"  width={200} height={200}  />
            <p>  </p>
            <p>  </p>
            <p> ”</p>
            <Image className={styles.christ} src="/2-jesus-christ-praying-on-his-knees-cartoon-clipart.jpeg" alt="title" width={200} height={200}  />
            <p> </p>
            <p> </p>
        </a>
        
        <a href="javascript:void(0)" className={styles.card1}>
         
         <h1 className={styles.h1}>
          Jesus &rarr;</h1>
        <p> </p>
        <Image className={styles.christ} src="/2-jesus-christ-praying-on-his-knees-cartoon-clipart.jpeg" alt="title" width={200} height={200}  />
        <p> </p>
        <p> </p>
        <p> </p>
        <Image className={styles.christ} src="/peace_jesus.jpeg" alt="jesus"  width={200} height={200}  />
        <p> </p>
        </a>


          <a href="javascript:void(0)" className={styles.card1}>
            <h2 className={styles.h1} >Jesus  &rarr;</h2>
            <Image className={styles.christ} src="/6-sad-jesus-christ-cartoon-clipart.jpeg" alt="jesus"  width={200} height={200}  />
            <p> </p>
            <Image className={styles.christ} src="/1-jesus-christ-with-arms-wide-open-cartoon-clipart.jpeg" alt="title" width={200} height={200}  />
            <p> </p>
            <p> </p>
           
 </a>
          
          <a
            href="javascript:void(0)"
            className={styles.card1}
          >
            <h2 className={styles.h1}> Jesus  &rarr;</h2>
          <p></p>
            <p>
            <Image className={styles.christ} src="/worship_jesus.jpeg" alt="title" width={200} height={200}  />
           Sentence goes here
            </p>
            <p>  </p>
            <p> </p>
            <p> </p>
            <p> </p>
            <p> </p>
            
          </a>

         

     
        </div>





      </main>
   
      <footer className={styles.footer}>
      
        <a
          href="javascript:void(0)"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
      
            <Image src="/6-sad-jesus-christ-cartoon-clipart.jpeg" alt="Vercel Logo" width={200} height={200} />
          </span>
        </a>
      </footer>
    </div>
  )
}
